name: Rust Pipeline

on:
  push:
    # branches:
    #   -main
      # -beta

jobs:
# Obtention de la version du projet
  # get-version:
  #   uses: shiipou/github-actions/.github/workflows/get-version.yml@main
  #   with:
  #     release-branches: '^(main)$'
  

  Install-Rust: 
    name: Rust build
    runs-on: ubuntu-latest
    # if: ${{ needs.get-version.outputs.will-release == 'true' }}
    # needs: 
    #   - get-version
    steps:
# Copie du code source
      - name: Checkout files
        uses: actions/checkout@v4.2.1
# Installation de rust toolchain
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true
# check version de rust
      - name: check rust version
        run: rustc --version
# # Install wasm
#       - name: Install Wasm
#         run: rustup target add wasm32-unknown-unknown
# # Build de wasm
#       - name: Build 
#         run: trunk build --release
# # Package
#       - name: Package
#         run: tar -czvf my-project.tar.gz -C dist .

          

    
    


    
